### ISSUE TITLE
URL for extra-tlds is defunct

### ISSUE THREAD

**Issue by msimerson** [haraka/haraka-tld#11]
The URL embedded in the [update_tld_files](https://github.com/haraka/haraka-tld/blob/master/update_tld_files) script no longer functions.

### potential options

* maintain stale file
* update script with new URL
* get rid of extra-tlds

**Comment by smfreegard** [comment]
I've pinged my contact at URIBL to find out why the file has disappeared.  I'll update this when I hear back.

**Comment by smfreegard** [comment]
Ok - it's fixed now.
