### ISSUE TITLE
update_tld_files should validate download

### ISSUE THREAD

**Issue by msimerson** [haraka/haraka-tld#12]
### Todo
- [x] update [update_tld_files](https://github.com/haraka/haraka-tld/blob/master/update_tld_files) to only save the downloaded file if it's a HTTP "happy" result code (ie, 200 or 304 (up-to-date)). 
- [ ] do some type of "tasting" of the file contents to assure the contents are valid

**Comment by msimerson** [comment]
#13 adds the curl -f option, which skips saving the file if a HTTP error is encountered. The curl -S option is also added so that the HTTP error is emitted to the console.

**Comment by PSSGCSim** [comment]
Maybe we can strip files of invalid records with grep and regex and then check the line count?

```
grep -Pi "^(\*\.|\!)?(?=^.{1,254}$)([\p{L}\p{N}_\-]+\.)*(?<tld>[\p{L}\p{N}]{2,})$" \
  filename > filename.new
```
This should match:
```
org
example.org
!texample.org
*.example.org
test.example.org
沖縄.jp
```

**Comment by msimerson** [comment]
Yep, that'd be a good approach. Strip out all the comments and whatnot, count the active records in the new file, compare the active records in the current file, and if it varies by more than ~10%, throw an error.

Another option is that, since this is in git repo, just download the new file, use a variant of `git diff` to count the add/subtracts, and compare that the total records in the file.

**Comment by PSSGCSim** [comment]
Also a good idea but it would miss accidental errors in source files. So I would probably go with the first one.
Is it open for PR? (I can make it)

**Comment by smfreegard** [comment]
> Is it open for PR? (I can make it)

You don't need to ask permission ;-)  Go right ahead!

**Comment by PSSGCSim** [comment]
I am trying to work out the regex... But I need some input on that.
Should I go with RFC and allow only ASCII encoded domains.
eg.
```
com
example.com
!example.com
*.example.com
xn--fsq470a1o74a
xn--fsq470a1o74a.jp
```

Or allow IDN where it becomes tricky as different registrars allow different things. Some registrars also allow emojis.
eg.
```
実例😊.jp
```

**Comment by PSSGCSim** [comment]
We could also take all `{2,255}` lines not starting with `//` or `# ` run them through the GNU `libidn` (https://serverfault.com/a/335110/172769). It takes domain name and returns punycode. It also does the basic verification like 255 characters.
I am not sure of system availability but GNU/Linux systems should have it. We can verify it though.

**Comment by PSSGCSim** [comment]
Ok, it is ready for testing from my side. You can check it out in my fork https://github.com/PSSGCSim/haraka-tld.
Please do and tell me what to change. I guess @msimerson will want me to refactor the code to match the project? If so please specify, I know the basics (https://github.com/haraka/Haraka/wiki/Contributing#style-conventions) but there are some BASH specific nuances.

example of changed usage:
```
[0]$ ./update_tld_files
Error: file "./etc/public-suffix-list" downloaded from "https://publicsuffix.org/list/effective_tld_names.dat"
       differs from the current file by more than 10% (old: 12287 vs new: 8357)
       specify --force to override and continue anyway
[7]$ ./update_tld_files --force
[0]$
```

**Comment by PSSGCSim** [comment]
As I found out it also fails the tests as everything is punycoded. What now? Simplify and leave domains as are or update code to punycode the input. I would go for the second one that is if I am not missing some points.

[test-case.log](https://github.com/haraka/haraka-tld/files/1384145/test-case.log)

**Comment by msimerson** [comment]
> "Should I go with RFC and allow only ASCII encoded domains...or IDN"

Do not IDN decode them. Anything in the PSL is legal and newer DNS RFCs have relaxed the ASCII restriction and the `haraka-tld` class uses the `punycode` module to handle comparison.
