### ISSUE TITLE
loaded TLD/suffix info should not be logged by default

### ISSUE THREAD

**Issue by jdc0589** [haraka/haraka-tld#29]
Currently, some information about TLD files and Public Suffixes gets logged to the console by default when haraka-tls is required/imported. This should not happen by default; any console output from a module like this should probably only be enabled conditionally.

**Comment by msimerson** [comment]
> This should not happen by default

That's one opinion, and there are others. Perhaps you could provide some reasoning for your opinion, as well as what conditions it would and would not be enabled during?

**Comment by jdc0589** [comment]
This probably isn't great reasoning since `haraka-tld` is probably only intended to be consumed by haraka, but its not useful to use a dependency in other applications that have a CLI/etc... if text meaningless to the end user is output in an uncontrollable way.

**Comment by msimerson** [comment]
Thanks for elaborating. We’d certainly consider a patch that permitted different logging behavior. Perhaps even passing in a logger when instantiated, so that the requiring library can control every aspect of logging.
